//! Z-Score Trigger Engine for Mean-Reversion Signals
//! 
//! Generates deterministic entry/exit signals based on 
//! standardized distance from OU mean.

use super::ou_process_modeler::OUParameters;
use core::sync::atomic::{AtomicBool, AtomicU64, Ordering};

/// Signal type generated by the Z-score trigger
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ZScoreSignal {
    /// No signal - spread within neutral zone
    None,
    /// Enter long spread (expect spread to increase)
    EnterLong,
    /// Enter short spread (expect spread to decrease)
    EnterShort,
    /// Exit long position
    ExitLong,
    /// Exit short position
    ExitShort,
    /// Emergency exit - extreme deviation
    EmergencyExit,
}

impl Default for ZScoreSignal {
    #[inline]
    fn default() -> Self {
        Self::None
    }
}

/// Configuration for Z-score thresholds
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ZScoreConfig {
    /// Entry threshold for long positions (negative z-score)
    pub entry_long: f64,
    /// Entry threshold for short positions (positive z-score)
    pub entry_short: f64,
    /// Exit threshold for long positions (mean reversion target)
    pub exit_long: f64,
    /// Exit threshold for short positions (mean reversion target)
    pub exit_short: f64,
    /// Emergency exit threshold (extreme deviation)
    pub emergency_threshold: f64,
    /// Hysteresis to prevent flip-flopping
    pub hysteresis: f64,
}

impl ZScoreConfig {
    /// Create a new config with standard thresholds
    #[inline]
    pub const fn standard() -> Self {
        Self {
            entry_long: -2.5,
            entry_short: 2.5,
            exit_long: 0.0,
            exit_short: 0.0,
            emergency_threshold: 4.0,
            hysteresis: 0.1,
        }
    }

    /// Create aggressive config (tighter thresholds)
    #[inline]
    pub const fn aggressive() -> Self {
        Self {
            entry_long: -1.5,
            entry_short: 1.5,
            exit_long: -0.5,
            exit_short: 0.5,
            emergency_threshold: 3.0,
            hysteresis: 0.05,
        }
    }

    /// Create conservative config (wider thresholds)
    #[inline]
    pub const fn conservative() -> Self {
        Self {
            entry_long: -3.5,
            entry_short: 3.5,
            exit_long: -1.0,
            exit_short: 1.0,
            emergency_threshold: 5.0,
            hysteresis: 0.2,
        }
    }
}

impl Default for ZScoreConfig {
    #[inline]
    fn default() -> Self {
        Self::standard()
    }
}

/// State of the current position
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PositionState {
    Flat,
    Long,
    Short,
}

impl Default for PositionState {
    #[inline]
    fn default() -> Self {
        Self::Flat
    }
}

/// Z-Score Trigger Engine
/// 
/// Generates trading signals based on OU process Z-scores
pub struct ZScoreTrigger {
    /// Current position state
    position: PositionState,
    /// Last computed Z-score
    last_zscore: f64,
    /// Configuration
    config: ZScoreConfig,
    /// Whether we're in hysteresis zone (preventing flip-flop)
    in_hysteresis: AtomicBool,
    /// Signal counter
    signal_count: AtomicU64,
    /// Last signal generated
    last_signal: ZScoreSignal,
}

impl ZScoreTrigger {
    /// Create a new Z-score trigger with given config
    #[inline]
    pub fn new(config: ZScoreConfig) -> Self {
        Self {
            position: PositionState::Flat,
            last_zscore: 0.0,
            config,
            in_hysteresis: AtomicBool::new(false),
            signal_count: AtomicU64::new(0),
            last_signal: ZScoreSignal::None,
        }
    }

    /// Evaluate the current Z-score and generate a signal
    /// 
    /// # Arguments
    /// * `zscore` - Current Z-score of the spread
    /// * `params` - Current OU parameters (for validation)
    /// 
    /// Returns the appropriate trading signal
    #[inline]
    pub fn evaluate(&mut self, zscore: f64, params: &OUParameters) -> ZScoreSignal {
        if !zscore.is_finite() || params.theta <= 0.0 {
            return ZScoreSignal::None;
        }

        self.last_zscore = zscore;

        // Check for emergency exit first
        if zscore.abs() > self.config.emergency_threshold {
            let signal = if self.position == PositionState::Long {
                ZScoreSignal::EmergencyExit
            } else if self.position == PositionState::Short {
                ZScoreSignal::EmergencyExit
            } else {
                ZScoreSignal::None
            };
            
            if signal != ZScoreSignal::None {
                self.record_signal(signal);
            }
            return signal;
        }

        let signal = match self.position {
            PositionState::Flat => {
                // Look for entry opportunities
                if zscore < self.config.entry_long {
                    ZScoreSignal::EnterLong
                } else if zscore > self.config.entry_short {
                    ZScoreSignal::EnterShort
                } else {
                    ZScoreSignal::None
                }
            }
            PositionState::Long => {
                // Currently long - look for exit or add
                if zscore > self.config.exit_long + self.config.hysteresis {
                    ZScoreSignal::ExitLong
                } else if zscore < self.config.entry_long - self.config.hysteresis {
                    // Already long, could add but typically don't
                    ZScoreSignal::None
                } else {
                    ZScoreSignal::None
                }
            }
            PositionState::Short => {
                // Currently short - look for exit or add
                if zscore < self.config.exit_short - self.config.hysteresis {
                    ZScoreSignal::ExitShort
                } else if zscore > self.config.entry_short + self.config.hysteresis {
                    // Already short, could add but typically don't
                    ZScoreSignal::None
                } else {
                    ZScoreSignal::None
                }
            }
        };

        if signal != ZScoreSignal::None {
            self.record_signal(signal);
        }

        signal
    }

    /// Record a signal and update state
    #[inline]
    fn record_signal(&mut self, signal: ZScoreSignal) {
        match signal {
            ZScoreSignal::EnterLong => self.position = PositionState::Long,
            ZScoreSignal::EnterShort => self.position = PositionState::Short,
            ZScoreSignal::ExitLong | ZScoreSignal::EmergencyExit => {
                if self.position == PositionState::Long {
                    self.position = PositionState::Flat;
                }
            }
            ZScoreSignal::ExitShort | ZScoreSignal::EmergencyExit => {
                if self.position == PositionState::Short {
                    self.position = PositionState::Flat;
                }
            }
            ZScoreSignal::None => {}
        }

        self.signal_count.fetch_add(1, Ordering::Relaxed);
        self.last_signal = signal;
    }

    /// Get the current position state
    #[inline]
    pub fn position(&self) -> PositionState {
        self.position
    }

    /// Get the last Z-score
    #[inline]
    pub fn last_zscore(&self) -> f64 {
        self.last_zscore
    }

    /// Get the last signal
    #[inline]
    pub fn last_signal(&self) -> ZScoreSignal {
        self.last_signal
    }

    /// Get the number of signals generated
    #[inline]
    pub fn signal_count(&self) -> u64 {
        self.signal_count.load(Ordering::Relaxed)
    }

    /// Reset the trigger to initial state
    #[inline]
    pub fn reset(&mut self) {
        self.position = PositionState::Flat;
        self.last_zscore = 0.0;
        self.in_hysteresis.store(false, Ordering::Relaxed);
        self.last_signal = ZScoreSignal::None;
    }

    /// Update the configuration
    #[inline]
    pub fn set_config(&mut self, config: ZScoreConfig) {
        self.config = config;
    }

    /// Get the current configuration
    #[inline]
    pub fn config(&self) -> &ZScoreConfig {
        &self.config
    }

    /// Check if currently in a valid mean-reverting regime
    /// (theta is high enough for reliable mean reversion)
    #[inline]
    pub fn is_valid_regime(&self, params: &OUParameters) -> bool {
        params.theta > 0.05 && params.half_life.is_finite() && params.half_life < 100.0
    }
}

impl Default for ZScoreTrigger {
    #[inline]
    fn default() -> Self {
        Self::new(ZScoreConfig::standard())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_entry_signals() {
        let mut trigger = ZScoreTrigger::new(ZScoreConfig::standard());
        let params = OUParameters::new(0.1, 0.0, 0.05);

        // Deep negative Z-score should trigger long entry
        let signal = trigger.evaluate(-3.0, &params);
        assert_eq!(signal, ZScoreSignal::EnterLong);
        assert_eq!(trigger.position(), PositionState::Long);

        // Reset and test short entry
        trigger.reset();
        let signal = trigger.evaluate(3.0, &params);
        assert_eq!(signal, ZScoreSignal::EnterShort);
        assert_eq!(trigger.position(), PositionState::Short);
    }

    #[test]
    fn test_exit_signals() {
        let mut trigger = ZScoreTrigger::new(ZScoreConfig::standard());
        let params = OUParameters::new(0.1, 0.0, 0.05);

        // Enter long first
        trigger.evaluate(-3.0, &params);
        assert_eq!(trigger.position(), PositionState::Long);

        // Mean reversion - Z-score returns to zero
        let signal = trigger.evaluate(0.5, &params);
        assert_eq!(signal, ZScoreSignal::ExitLong);
        assert_eq!(trigger.position(), PositionState::Flat);
    }

    #[test]
    fn test_emergency_exit() {
        let mut trigger = ZScoreTrigger::new(ZScoreConfig::standard());
        let params = OUParameters::new(0.1, 0.0, 0.05);

        // Enter long
        trigger.evaluate(-3.0, &params);
        
        // Extreme move against position
        let signal = trigger.evaluate(-5.0, &params);
        assert_eq!(signal, ZScoreSignal::EmergencyExit);
    }

    #[test]
    fn test_hysteresis() {
        let mut trigger = ZScoreTrigger::new(ZScoreConfig::standard());
        let params = OUParameters::new(0.1, 0.0, 0.05);

        // Enter long at -2.5
        trigger.evaluate(-2.6, &params);
        assert_eq!(trigger.position(), PositionState::Long);

        // Small bounce shouldn't trigger exit due to hysteresis
        let signal = trigger.evaluate(-0.05, &params);
        assert_eq!(signal, ZScoreSignal::None); // Still in hysteresis zone

        // Larger bounce should trigger exit
        let signal = trigger.evaluate(0.15, &params);
        assert_eq!(signal, ZScoreSignal::ExitLong);
    }

    #[test]
    fn test_nan_handling() {
        let mut trigger = ZScoreTrigger::default();
        let params = OUParameters::new(0.1, 0.0, 0.05);

        let signal = trigger.evaluate(f64::NAN, &params);
        assert_eq!(signal, ZScoreSignal::None);
    }

    #[test]
    fn test_invalid_regime() {
        let mut trigger = ZScoreTrigger::default();
        let params = OUParameters::new(0.0, 0.0, 0.05); // theta = 0, not mean-reverting

        assert!(!trigger.is_valid_regime(&params));

        let valid_params = OUParameters::new(0.1, 0.0, 0.05);
        assert!(trigger.is_valid_regime(&valid_params));
    }
}
