//! Botnet Pump-and-Dump Short Strategy
//! 
//! Implements trading logic that aggressively shorts assets when coordinated
//! botnet manipulation is detected, while simultaneously buying "truth proxy" assets.

use crate::warfare::spectral_astroturfing_detector::{
    AstroturfingAnalysis, PropagationClassification, AstroturfingAction,
};
use crate::warfare::fiedler_vector_graph::FiedlerAnalysis;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum BotnetTradingError {
    #[error("Insufficient confidence for trade: {confidence}")]
    InsufficientConfidence { confidence: f64 },
    #[error("Market conditions unsuitable for short")]
    UnsuitableMarketConditions,
    #[error("Position size calculation failed")]
    PositionSizeError,
    #[error("No truth proxy available for narrative")]
    NoTruthProxy,
}

/// Configuration for botnet trading strategy
#[derive(Debug, Clone)]
pub struct BotnetTradingConfig {
    /// Minimum confidence threshold to enter trade
    pub min_confidence: f64,
    /// Maximum position size as fraction of portfolio
    pub max_position_fraction: f64,
    /// Stop loss multiplier (e.g., 2.0 = 2x entry price)
    pub stop_loss_multiplier: f64,
    /// Take profit fraction (e.g., 0.5 = take profit at 50% decline)
    pub take_profit_fraction: f64,
    /// Scaling factor for position based on confidence
    pub confidence_scaling: bool,
    /// Whether to buy truth proxy when shorting
    pub buy_truth_proxy: bool,
}

impl Default for BotnetTradingConfig {
    fn default() -> Self {
        Self {
            min_confidence: 0.7,
            max_position_fraction: 0.15,
            stop_loss_multiplier: 2.0,
            take_profit_fraction: 0.5,
            confidence_scaling: true,
            buy_truth_proxy: true,
        }
    }
}

/// Trade signal generated by botnet detection
#[derive(Debug, Clone)]
pub struct BotnetShortSignal {
    /// Asset to short
    pub short_asset: String,
    /// Truth proxy asset to buy (optional)
    pub truth_proxy: Option<String>,
    /// Recommended position size (fraction of portfolio)
    pub position_size: f64,
    /// Entry price level
    pub entry_price: f64,
    /// Stop loss price
    pub stop_loss_price: f64,
    /// Take profit price
    pub take_profit_price: f64,
    /// Confidence in botnet detection
    pub confidence: f64,
    /// Classification that triggered signal
    pub classification: PropagationClassification,
    /// Fiedler analysis backing the signal
    pub fiedler_analysis: Option<FiedlerAnalysis>,
    /// Urgency score [0, 1]
    pub urgency: f64,
}

impl BotnetShortSignal {
    /// Check if signal meets minimum confidence threshold
    pub fn meets_threshold(&self, threshold: f64) -> bool {
        self.confidence >= threshold
    }

    /// Expected risk/reward ratio
    pub fn risk_reward_ratio(&self) -> Option<f64> {
        let risk = self.stop_loss_price - self.entry_price;
        let reward = self.entry_price - self.take_profit_price;
        
        if risk <= 0.0 || reward <= 0.0 {
            return None;
        }
        
        Some(reward / risk)
    }

    /// Position adjusted for confidence
    pub fn confidence_adjusted_position(&self, base_size: f64) -> f64 {
        base_size * self.confidence
    }
}

/// Main botnet pump-and-dump detector and trader
pub struct BotnetPumpShortStrategy {
    config: BotnetTradingConfig,
    /// Track detected pump schemes
    active_schemes: Vec<ActivePumpScheme>,
}

impl BotnetPumpShortStrategy {
    pub fn new(config: BotnetTradingConfig) -> Self {
        Self {
            config,
            active_schemes: Vec::new(),
        }
    }

    /// Analyze astroturfing detection and generate trade signal
    pub fn analyze_and_generate_signal(
        &self,
        asset: &str,
        current_price: f64,
        analysis: &AstroturfingAnalysis,
        fiedler_analysis: Option<&FiedlerAnalysis>,
    ) -> Result<BotnetShortSignal, BotnetTradingError> {
        // Check confidence threshold
        if analysis.botnet_confidence < self.config.min_confidence {
            return Err(BotnetTradingError::InsufficientConfidence {
                confidence: analysis.botnet_confidence,
            });
        }

        // Only trade on confirmed or likely botnet classifications
        match analysis.classification {
            PropagationClassification::ConfirmedBotnet
            | PropagationClassification::LikelyBotnet => {}
            _ => {
                return Err(BotnetTradingError::UnsuitableMarketConditions);
            }
        }

        // Calculate position size
        let base_size = self.config.max_position_fraction;
        let position_size = if self.config.confidence_scaling {
            base_size * analysis.botnet_confidence
        } else {
            base_size
        };

        // Calculate price levels
        let stop_loss_price = current_price * self.config.stop_loss_multiplier;
        let take_profit_price = current_price * (1.0 - self.config.take_profit_fraction);

        // Determine truth proxy based on narrative type
        let truth_proxy = if self.config.buy_truth_proxy {
            self.find_truth_proxy(asset, analysis)
        } else {
            None
        };

        // Calculate urgency based on structural metrics
        let urgency = self.calculate_urgency(analysis, fiedler_analysis);

        Ok(BotnetShortSignal {
            short_asset: asset.to_string(),
            truth_proxy,
            position_size,
            entry_price: current_price,
            stop_loss_price,
            take_profit_price,
            confidence: analysis.botnet_confidence,
            classification: analysis.classification,
            fiedler_analysis: fiedler_analysis.cloned(),
            urgency,
        })
    }

    fn find_truth_proxy(&self, asset: &str, _analysis: &AstroturfingAnalysis) -> Option<String> {
        // In production, this would query a database of truth proxies
        // For now, return based on common patterns
        match asset {
            "GME" => Some("IBKR"),  // Brokerage benefits from volatility
            "AMC" => Some("CNK"),  // Competitor cinema chain
            "BBBY" => None,         // No clear proxy (bankrupt)
            "DOGE" => Some("COIN"), // Crypto exchange
            _ => {
                // Generic: use market inverse ETF or volatility product
                Some("VIX")
            }
        }
    }

    fn calculate_urgency(
        &self,
        analysis: &AstroturfingAnalysis,
        fiedler_analysis: Option<&FiedlerAnalysis>,
    ) -> f64 {
        let mut urgency = 0.5;

        // Higher urgency for confirmed botnets
        if analysis.classification == PropagationClassification::ConfirmedBotnet {
            urgency += 0.3;
        }

        // Higher urgency for low Fiedler value (clear hub-spoke)
        if let Some(fiedler) = fiedler_analysis {
            if fiedler.fiedler_value < 0.1 {
                urgency += 0.2;
            }
            
            // Hub-spoke pattern increases urgency
            if fiedler.interpretation == crate::warfare::fiedler_vector_graph::FiedlerInterpretation::HubSpoke {
                urgency += 0.15;
            }
        }

        // High bot fraction increases urgency
        if analysis.estimated_bot_fraction > 0.5 {
            urgency += 0.1;
        }

        urgency.min(1.0)
    }

    /// Register an active pump scheme for monitoring
    pub fn register_scheme(&mut self, signal: &BotnetShortSignal) {
        self.active_schemes.push(ActivePumpScheme {
            asset: signal.short_asset.clone(),
            entry_price: signal.entry_price,
            entry_time: 0.0, // Would be set by caller
            peak_price: signal.entry_price,
            status: PumpStatus::Active,
        });
    }

    /// Update scheme status based on price movement
    pub fn update_scheme(&mut self, asset: &str, current_price: f64) -> Option<SchemeUpdate> {
        let scheme = self.active_schemes.iter_mut().find(|s| s.asset == asset)?;
        
        if current_price > scheme.peak_price {
            scheme.peak_price = current_price;
        }

        let drawdown = (scheme.peak_price - current_price) / scheme.peak_price;
        
        let new_status = if drawdown > self.config.take_profit_fraction {
            PumpStatus::TargetHit
        } else if current_price > scheme.stop_loss_price {
            PumpStatus::StoppedOut
        } else {
            PumpStatus::Active
        };

        let status_changed = scheme.status != new_status;
        scheme.status = new_status;

        if status_changed {
            Some(SchemeUpdate {
                asset: asset.to_string(),
                old_status: new_status, // Previous status
                new_status,
                current_drawdown: drawdown,
            })
        } else {
            None
        }
    }

    /// Get all active schemes
    pub fn active_schemes(&self) -> &[ActivePumpScheme] {
        &self.active_schemes
    }

    /// Close completed schemes
    pub fn close_completed(&mut self) -> Vec<ActivePumpScheme> {
        let (completed, remaining): (Vec<_>, Vec<_>) = self.active_schemes
            .drain(..)
            .partition(|s| s.is_completed());
        
        self.active_schemes = remaining;
        completed
    }
}

/// Status of a tracked pump scheme
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PumpStatus {
    Active,
    TargetHit,
    StoppedOut,
    ManuallyClosed,
}

/// Active pump scheme being monitored
#[derive(Debug, Clone)]
pub struct ActivePumpScheme {
    pub asset: String,
    pub entry_price: f64,
    pub entry_time: f64,
    pub peak_price: f64,
    pub status: PumpStatus,
}

impl ActivePumpScheme {
    pub fn is_completed(&self) -> bool {
        matches!(self.status, PumpStatus::TargetHit | PumpStatus::StoppedOut | PumpStatus::ManuallyClosed)
    }

    pub fn current_pnl(&self, current_price: f64) -> f64 {
        (self.entry_price - current_price) / self.entry_price
    }

    pub fn max_pnl_achieved(&self) -> f64 {
        (self.entry_price - self.peak_price) / self.entry_price
    }
}

/// Update notification for scheme status changes
#[derive(Debug, Clone)]
pub struct SchemeUpdate {
    pub asset: String,
    pub old_status: PumpStatus,
    pub new_status: PumpStatus,
    pub current_drawdown: f64,
}

/// Portfolio manager for botnet trades
pub struct BotnetPortfolioManager {
    strategies: Vec<BotnetPumpShortStrategy>,
    total_exposure: f64,
    max_total_exposure: f64,
}

impl BotnetPortfolioManager {
    pub fn new(max_total_exposure: f64) -> Self {
        Self {
            strategies: Vec::new(),
            total_exposure: 0.0,
            max_total_exposure,
        }
    }

    /// Add a strategy instance
    pub fn add_strategy(&mut self, strategy: BotnetPumpShortStrategy) {
        self.strategies.push(strategy);
    }

    /// Check if there's capacity for new positions
    pub fn has_capacity(&self, required_exposure: f64) -> bool {
        self.total_exposure + required_exposure <= self.max_total_exposure
    }

    /// Allocate exposure for a new position
    pub fn allocate_exposure(&mut self, amount: f64) -> bool {
        if self.has_capacity(amount) {
            self.total_exposure += amount;
            true
        } else {
            false
        }
    }

    /// Release exposure when position closes
    pub fn release_exposure(&mut self, amount: f64) {
        self.total_exposure = (self.total_exposure - amount).max(0.0);
    }

    /// Current utilization
    pub fn utilization(&self) -> f64 {
        self.total_exposure / self.max_total_exposure
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::warfare::spectral_astroturfing_detector::{GraphMetrics, PropagationClassification};

    #[test]
    fn test_signal_generation() {
        let config = BotnetTradingConfig::default();
        let strategy = BotnetPumpShortStrategy::new(config);

        let analysis = AstroturfingAnalysis {
            fiedler_value: 0.05,
            fiedler_vector: None,
            botnet_confidence: 0.85,
            estimated_bot_fraction: 0.6,
            structural_metrics: GraphMetrics {
                node_count: 100,
                edge_count: 150,
                avg_degree: 3.0,
                clustering_coefficient: 0.1,
                diameter: None,
                density: 0.03,
            },
            classification: PropagationClassification::LikelyBotnet,
        };

        let signal = strategy.analyze_and_generate_signal("TEST", 100.0, &analysis, None);
        
        assert!(signal.is_ok());
        let sig = signal.unwrap();
        assert_eq!(sig.short_asset, "TEST");
        assert!(sig.position_size > 0.0);
        assert!(sig.confidence >= 0.7);
    }

    #[test]
    fn test_low_confidence_rejection() {
        let config = BotnetTradingConfig::default();
        let strategy = BotnetPumpShortStrategy::new(config);

        let analysis = AstroturfingAnalysis {
            fiedler_value: 0.5,
            fiedler_vector: None,
            botnet_confidence: 0.4,
            estimated_bot_fraction: 0.2,
            structural_metrics: GraphMetrics {
                node_count: 50,
                edge_count: 100,
                avg_degree: 4.0,
                clustering_coefficient: 0.3,
                diameter: None,
                density: 0.08,
            },
            classification: PropagationClassification::Suspicious,
        };

        let signal = strategy.analyze_and_generate_signal("TEST", 100.0, &analysis, None);
        
        assert!(signal.is_err());
    }
}
