//! Build script for nexus_core
//! 
//! This script:
//! 1. Generates C headers for FFI bindings
//! 2. Checks for required system libraries (libpcap, rdkafka)
//! 3. Configures linker flags for optimal performance

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=include/nexus_core.h");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    // Generate C header file for FFI
    generate_c_header(&out_dir);

    // Check for system dependencies
    check_system_dependencies();

    // Configure platform-specific optimizations
    configure_platform_optimizations();

    // Copy generated header to include directory
    let include_dir = manifest_dir.join("include");
    fs::create_dir_all(&include_dir).expect("Failed to create include directory");
    fs::copy(
        out_dir.join("nexus_core.h"),
        include_dir.join("nexus_core.h"),
    ).expect("Failed to copy header file");
}

fn generate_c_header(out_dir: &Path) {
    let header_content = r#"/* 
 * NEXUS-OMEGA Core FFI Header
 * Auto-generated by build.rs - DO NOT EDIT MANUALLY
 */

#ifndef NEXUS_CORE_H
#define NEXUS_CORE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Memory Arena Opaque Types */
typedef struct NexusBumpAllocator NexusBumpAllocator;
typedef struct NexusCachePadded64 NexusCachePadded64;

/* SPSC Ring Buffer Types */
typedef struct NexusSPSCRingBuffer NexusSPSCRingBuffer;
typedef struct NexusRingSlot NexusRingSlot;

/* Event Bus Types */
typedef struct NexusMessageBus NexusMessageBus;
typedef struct NexusEventHeader NexusEventHeader;

/* Time/Clock Types */
typedef struct NexusMonotonicClock NexusMonotonicClock;
typedef uint64_t NexusTimestampNanos;

/* Error Codes */
typedef enum {
    NEXUS_OK = 0,
    NEXUS_ERR_OUT_OF_MEMORY = 1,
    NEXUS_ERR_BUFFER_FULL = 2,
    NEXUS_ERR_BUFFER_EMPTY = 3,
    NEXUS_ERR_INVALID_ARGUMENT = 4,
    NEXUS_ERR_FFI_BOUNDARY = 5,
    NEXUS_ERR_TIME_SYNC = 6,
} NexusErrorCode;

/* Result type for FFI calls */
typedef struct {
    NexusErrorCode code;
    void* data;
} NexusResult;

/* ==================== Memory Arena API ==================== */

NexusBumpAllocator* nexus_arena_create(size_t capacity_bytes);
void nexus_arena_destroy(NexusBumpAllocator* arena);
void* nexus_arena_alloc(NexusBumpAllocator* arena, size_t size, size_t align);
void nexus_arena_reset(NexusBumpAllocator* arena);
size_t nexus_arena_allocated_bytes(const NexusBumpAllocator* arena);
size_t nexus_arena_remaining_bytes(const NexusBumpAllocator* arena);

/* ==================== SPSC Ring Buffer API ==================== */

NexusSPSCRingBuffer* nexus_spsc_create(size_t capacity_slots);
void nexus_spsc_destroy(NexusSPSCRingBuffer* ring);
NexusErrorCode nexus_spsc_push(NexusSPSCRingBuffer* ring, const void* data, size_t len);
NexusErrorCode nexus_spsc_pop(NexusSPSCRingBuffer* ring, void* out_data, size_t* out_len);
bool nexus_spsc_is_empty(const NexusSPSCRingBuffer* ring);
bool nexus_spsc_is_full(const NexusSPSCRingBuffer* ring);
size_t nexus_spsc_size(const NexusSPSCRingBuffer* ring);

/* ==================== Message Bus API ==================== */

NexusMessageBus* nexus_message_bus_create(size_t channel_capacity);
void nexus_message_bus_destroy(NexusMessageBus* bus);
NexusErrorCode nexus_message_bus_publish(
    NexusMessageBus* bus,
    const char* channel,
    const void* data,
    size_t len
);
NexusErrorCode nexus_message_bus_subscribe(
    NexusMessageBus* bus,
    const char* channel,
    void (*callback)(const void*, size_t, void*),
    void* user_data
);

/* ==================== Monotonic Clock API ==================== */

NexusMonotonicClock* nexus_monotonic_clock_create(void);
void nexus_monotonic_clock_destroy(NexusMonotonicClock* clock);
NexusTimestampNanos nexus_monotonic_clock_now_nanos(const NexusMonotonicClock* clock);
NexusTimestampNanos nexus_monotonic_clock_delta_nanos(
    const NexusMonotonicClock* clock,
    NexusTimestampNanos start,
    NexusTimestampNanos end
);
double nexus_monotonic_clock_elapsed_micros(
    const NexusMonotonicClock* clock,
    NexusTimestampNanos start
);

#ifdef __cplusplus
}
#endif

#endif /* NEXUS_CORE_H */
"#;

    let header_path = out_dir.join("nexus_core.h");
    fs::write(header_path, header_content).expect("Failed to write header file");
}

fn check_system_dependencies() {
    // Check for libpcap
    if !check_library_exists("pcap") {
        println!("cargo:warning=libpcap not found. Some network capture features may be unavailable.");
        println!("cargo:rustc-link-lib=dylib=pcap");
    } else {
        println!("cargo:rustc-link-lib=dylib=pcap");
    }

    // Check for rdkafka
    if !check_library_exists("rdkafka") {
        println!("cargo:warning=librdkafka not found. Kafka integration will be unavailable.");
        println!("cargo:rustc-link-lib=dylib=rdkafka");
    } else {
        println!("cargo:rustc-link-lib=dylib=rdkafka");
    }
}

fn check_library_exists(lib_name: &str) -> bool {
    // Try to find the library using pkg-config or ldconfig
    Command::new("pkg-config")
        .arg("--exists")
        .arg(lib_name)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn configure_platform_optimizations() {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    
    match target_arch.as_str() {
        "x86_64" => {
            println!("cargo:rustc-cfg=target_feature=\"sse2\"");
            println!("cargo:rustc-cfg=target_feature=\"ssse3\"");
            println!("cargo:rustc-cfg=target_feature=\"sse4.1\"");
            println!("cargo:rustc-cfg=target_feature=\"sse4.2\"");
            #[cfg(target_feature = "avx2")]
            println!("cargo:rustc-cfg=target_feature=\"avx2\"");
        }
        "aarch64" => {
            println!("cargo:rustc-cfg=target_feature=\"neon\"");
        }
        _ => {}
    }

    // Enable link-time optimization hints
    println!("cargo:rustc-link-arg=-Wl,--as-needed");
    
    // Prefer position-independent executables for shared library usage
    println!("cargo:rustc-cdylib-link-arg=-fPIC");
}
