"""
NEXUS-OMEGA Stage 19: Deterministic Flatten FSM for Recovery

This module implements a deterministic finite state machine (FSM) for
emergency portfolio flattening when the recovery policy is triggered.
It provides a strictly hard-coded, auditable liquidation sequence that
cannot be overridden by the RL agent.

States:
1. IDLE - No liquidation needed
2. ASSESSING - Evaluating positions to liquidate
3. REDUCING_RISK - Gradual position reduction
4. AGGRESSIVE_SELL - Faster liquidation
5. FLATTENING - Emergency flatten all positions
6. COMPLETE - Liquidation finished

Author: NEXUS-OMEGA Architecture
Stage: 19 of 50
"""

from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any
import time


class FlattenState(Enum):
    """States in the liquidation FSM."""
    IDLE = auto()
    ASSESSING = auto()
    REDUCING_RISK = auto()
    AGGRESSIVE_SELL = auto()
    FLATTENING = auto()
    COMPLETE = auto()
    ERROR = auto()


@dataclass
class PositionInfo:
    """Information about a position to liquidate."""
    asset_id: str
    quantity: float
    side: str  # 'long' or 'short'
    entry_price: float
    current_price: float
    unrealized_pnl: float
    liquidity_score: float  # 0-1, higher = more liquid
    urgency_weight: float   # Higher = liquidate first


@dataclass
class LiquidationOrder:
    """An order generated by the FSM."""
    asset_id: str
    side: str  # 'buy' or 'sell'
    quantity: float
    order_type: str  # 'market', 'limit', 'iceberg', 'twap'
    limit_price: Optional[float] = None
    display_qty: Optional[float] = None  # For iceberg
    urgency: float = 0.0  # 0-1


@dataclass
class FSMTransition:
    """A transition in the FSM."""
    from_state: FlattenState
    to_state: FlattenState
    condition: str
    action: str


class DeterministicFlattenFSM:
    """
    Deterministic finite state machine for emergency liquidation.
    
    All transitions are hard-coded and auditable. No RL agent can
    override the liquidation logic once triggered.
    """
    
    def __init__(self):
        self.current_state = FlattenState.IDLE
        self.positions: Dict[str, PositionInfo] = {}
        self.pending_orders: List[LiquidationOrder] = []
        self.executed_orders: List[LiquidationOrder] = []
        self.liquidation_progress: Dict[str, float] = {}  # asset_id -> fraction complete
        
        # Configuration
        self.reduce_step_size = 0.2  # 20% reduction per step in REDUCING_RISK
        self.aggressive_threshold = 0.5  # Switch to aggressive at 50% progress
        self.max_orders_per_cycle = 10
        
        # Timing
        self.state_entry_time: Optional[float] = None
        self.last_action_time: Optional[float] = None
        self.min_action_interval = 0.1  # seconds
        
        # Statistics
        self.total_liquidated_value = 0.0
        self.slippage_total = 0.0
    
    def transition_to(self, new_state: FlattenState, reason: str = "") -> bool:
        """
        Attempt to transition to a new state.
        
        Returns True if transition occurred, False if invalid.
        """
        valid_transitions = {
            FlattenState.IDLE: [FlattenState.ASSESSING, FlattenState.IDLE],
            FlattenState.ASSESSING: [FlattenState.REDUCING_RISK, FlattenState.FLATTENING, FlattenState.ERROR],
            FlattenState.REDUCING_RISK: [FlattenState.AGGRESSIVE_SELL, FlattenState.FLATTENING, FlattenState.COMPLETE, FlattenState.ERROR],
            FlattenState.AGGRESSIVE_SELL: [FlattenState.FLATTENING, FlattenState.COMPLETE, FlattenState.ERROR],
            FlattenState.FLATTENING: [FlattenState.COMPLETE, FlattenState.ERROR],
            FlattenState.COMPLETE: [FlattenState.IDLE],
            FlattenState.ERROR: [FlattenState.IDLE, FlattenState.ASSESSING],
        }
        
        allowed = valid_transitions.get(self.current_state, [])
        if new_state not in allowed:
            return False
        
        # Execute exit action for current state
        self._on_exit_state()
        
        # Transition
        old_state = self.current_state
        self.current_state = new_state
        self.state_entry_time = time.time()
        
        # Execute entry action for new state
        self._on_enter_state(new_state, reason)
        
        return True
    
    def _on_exit_state(self) -> None:
        """Actions taken when exiting a state."""
        pass
    
    def _on_enter_state(self, state: FlattenState, reason: str) -> None:
        """Actions taken when entering a state."""
        if state == FlattenState.ASSESSING:
            self._assess_positions()
        elif state == FlattenState.REDUCING_RISK:
            self._generate_reduce_orders()
        elif state == FlattenState.AGGRESSIVE_SELL:
            self._generate_aggressive_orders()
        elif state == FlattenState.FLATTENING:
            self._generate_flatten_orders()
        elif state == FlattenState.COMPLETE:
            self._on_liquidation_complete()
        elif state == FlattenState.ERROR:
            self._handle_error(reason)
    
    def _assess_positions(self) -> None:
        """Assess all positions and prioritize liquidation order."""
        if not self.positions:
            self.transition_to(FlattenState.COMPLETE, "No positions to liquidate")
            return
        
        # Compute urgency weights based on risk metrics
        for asset_id, pos in self.positions.items():
            # Higher urgency for:
            # - Larger positions
            # - Worse PnL
            # - Lower liquidity (need to exit sooner)
            size_weight = min(1.0, abs(pos.quantity) / 1000.0)
            pnl_weight = max(0, -pos.unrealized_pnl / 10000.0)  # Penalize losses
            liq_weight = 1.0 - pos.liquidity_score
            
            pos.urgency_weight = size_weight * 0.4 + pnl_weight * 0.4 + liq_weight * 0.2
        
        # Initialize progress tracking
        for asset_id in self.positions:
            self.liquidation_progress[asset_id] = 0.0
        
        # Transition to reducing
        self.transition_to(FlattenState.REDUCING_RISK, "Positions assessed")
    
    def _generate_reduce_orders(self) -> None:
        """Generate orders for gradual risk reduction."""
        self.pending_orders = []
        
        # Sort positions by urgency
        sorted_positions = sorted(
            self.positions.values(),
            key=lambda p: p.urgency_weight,
            reverse=True
        )
        
        for pos in sorted_positions[:self.max_orders_per_cycle]:
            remaining = pos.quantity * (1 - self.liquidation_progress.get(pos.asset_id, 0))
            reduce_qty = remaining * self.reduce_step_size
            
            if abs(reduce_qty) < 0.01:  # Minimum order size
                continue
            
            order_side = 'sell' if pos.quantity > 0 else 'buy'
            
            order = LiquidationOrder(
                asset_id=pos.asset_id,
                side=order_side,
                quantity=abs(reduce_qty),
                order_type='limit',
                limit_price=pos.current_price * (0.995 if order_side == 'sell' else 1.005),
                urgency=pos.urgency_weight * 0.5,
            )
            self.pending_orders.append(order)
        
        # Check if we should escalate
        total_progress = sum(self.liquidation_progress.values()) / max(len(self.positions), 1)
        if total_progress > self.aggressive_threshold:
            self.transition_to(FlattenState.AGGRESSIVE_SELL, "Reached aggressive threshold")
    
    def _generate_aggressive_orders(self) -> None:
        """Generate more aggressive liquidation orders."""
        self.pending_orders = []
        
        for pos in self.positions.values():
            remaining = pos.quantity * (1 - self.liquidation_progress.get(pos.asset_id, 0))
            reduce_qty = remaining * 0.5  # 50% reduction
            
            if abs(reduce_qty) < 0.01:
                continue
            
            order_side = 'sell' if pos.quantity > 0 else 'buy'
            
            # Use iceberg for larger orders
            if abs(reduce_qty) > 100:
                order = LiquidationOrder(
                    asset_id=pos.asset_id,
                    side=order_side,
                    quantity=abs(reduce_qty),
                    order_type='iceberg',
                    limit_price=pos.current_price * (0.99 if order_side == 'sell' else 1.01),
                    display_qty=abs(reduce_qty) * 0.1,
                    urgency=0.7,
                )
            else:
                order = LiquidationOrder(
                    asset_id=pos.asset_id,
                    side=order_side,
                    quantity=abs(reduce_qty),
                    order_type='limit',
                    limit_price=pos.current_price * (0.99 if order_side == 'sell' else 1.01),
                    urgency=0.7,
                )
            self.pending_orders.append(order)
    
    def _generate_flatten_orders(self) -> None:
        """Generate emergency flatten-all orders."""
        self.pending_orders = []
        
        for pos in self.positions.values():
            remaining = pos.quantity * (1 - self.liquidation_progress.get(pos.asset_id, 0))
            
            if abs(remaining) < 0.01:
                continue
            
            order_side = 'sell' if pos.quantity > 0 else 'buy'
            
            # Market orders for immediate execution
            order = LiquidationOrder(
                asset_id=pos.asset_id,
                side=order_side,
                quantity=abs(remaining),
                order_type='market',
                urgency=1.0,
            )
            self.pending_orders.append(order)
    
    def report_order_execution(
        self,
        asset_id: str,
        executed_qty: float,
        exec_price: float,
        expected_price: float,
    ) -> None:
        """Report that an order was executed."""
        if asset_id in self.positions:
            pos = self.positions[asset_id]
            
            # Update progress
            total_qty = abs(pos.quantity)
            previously_done = self.liquidation_progress.get(asset_id, 0) * total_qty
            new_progress = (previously_done + executed_qty) / total_qty
            self.liquidation_progress[asset_id] = min(1.0, new_progress)
            
            # Track slippage
            slippage = abs(exec_price - expected_price) / expected_price
            self.slippage_total += slippage * executed_qty * exec_price
            self.total_liquidated_value += executed_qty * exec_price
        
        # Check completion
        self._check_completion()
    
    def _check_completion(self) -> None:
        """Check if liquidation is complete."""
        if self.current_state not in [
            FlattenState.REDUCING_RISK,
            FlattenState.AGGRESSIVE_SELL,
            FlattenState.FLATTENING,
        ]:
            return
        
        all_complete = all(
            prog >= 0.99 for prog in self.liquidation_progress.values()
        ) if self.liquidation_progress else True
        
        if all_complete:
            self.transition_to(FlattenState.COMPLETE, "All positions liquidated")
    
    def _on_liquidation_complete(self) -> None:
        """Called when liquidation is complete."""
        # Clear positions
        self.positions.clear()
        self.pending_orders.clear()
    
    def _handle_error(self, reason: str) -> None:
        """Handle error state."""
        print(f"FLATTEN FSM ERROR: {reason}")
        # In production, this would trigger alerts
    
    def update_position(self, asset_id: str, info: PositionInfo) -> None:
        """Update position information."""
        self.positions[asset_id] = info
    
    def remove_position(self, asset_id: str) -> None:
        """Remove a position (externally liquidated)."""
        if asset_id in self.positions:
            del self.positions[asset_id]
        if asset_id in self.liquidation_progress:
            del self.liquidation_progress[asset_id]
    
    def get_pending_orders(self) -> List[LiquidationOrder]:
        """Get pending orders, respecting rate limits."""
        now = time.time()
        
        if self.last_action_time is not None:
            if now - self.last_action_time < self.min_action_interval:
                return []
        
        self.last_action_time = now
        return self.pending_orders.copy()
    
    def clear_orders(self) -> None:
        """Clear pending orders after execution."""
        self.executed_orders.extend(self.pending_orders)
        self.pending_orders.clear()
    
    def reset(self) -> None:
        """Reset FSM to initial state."""
        self.current_state = FlattenState.IDLE
        self.positions.clear()
        self.pending_orders.clear()
        self.executed_orders.clear()
        self.liquidation_progress.clear()
        self.total_liquidated_value = 0.0
        self.slippage_total = 0.0
    
    def get_status(self) -> Dict[str, Any]:
        """Get current FSM status."""
        return {
            'state': self.current_state.name,
            'positions_count': len(self.positions),
            'pending_orders': len(self.pending_orders),
            'liquidation_progress': self.liquidation_progress.copy(),
            'total_liquidated': self.total_liquidated_value,
            'total_slippage': self.slippage_total,
            'state_duration': time.time() - self.state_entry_time if self.state_entry_time else 0,
        }


# Singleton instance for global access
_flatten_fsm_instance: Optional[DeterministicFlattenFSM] = None


def get_flatten_fsm() -> DeterministicFlattenFSM:
    """Get the global singleton FSM instance."""
    global _flatten_fsm_instance
    if _flatten_fsm_instance is None:
        _flatten_fsm_instance = DeterministicFlattenFSM()
    return _flatten_fsm_instance


def trigger_emergency_flatten(positions: Dict[str, PositionInfo]) -> None:
    """Trigger emergency liquidation from external code."""
    fsm = get_flatten_fsm()
    
    for asset_id, info in positions.items():
        fsm.update_position(asset_id, info)
    
    fsm.transition_to(FlattenState.ASSESSING, "Emergency trigger")
