//! EVM Bytecode Quine Generator with Gas Exhaustion Protection
//!
//! Generates self-referential EVM bytecode that contains its own hash
//! and can atomically replicate to new addresses.

use alloc::vec::Vec;
use core::marker::PhantomData;

/// Error types for EVM quine generation
#[derive(Debug, Clone, PartialEq)]
pub enum QuineError {
    BytecodeTooLarge,
    GasEstimateFailed,
    InvalidConstructor,
    HashMismatch,
}

/// Result type for quine operations
pub type QuineResult<T> = Result<T, QuineError>;

/// EVM bytecode opcodes
mod opcodes {
    pub const PUSH32: u8 = 0x7F;
    pub const PUSH1: u8 = 0x60;
    pub const DUP1: u8 = 0x80;
    pub const CODECOPY: u8 = 0x39;
    pub const RETURN: u8 = 0xF3;
    pub const CREATE: u8 = 0xF0;
    pub const CALL: u8 = 0xF1;
    pub const SHA3: u8 = 0x20;
    pub const EQ: u8 = 0x14;
    pub const REVERT: u8 = 0xFD;
}

/// Configuration for quine generation
#[derive(Debug, Clone)]
pub struct QuineConfig {
    /// Maximum bytecode size (default: 24 KiB EVM limit)
    pub max_bytecode_size: usize,
    /// Gas estimation buffer multiplier (default: 1.1 = 10% buffer)
    pub gas_buffer_multiplier: f64,
    /// Standard block gas limit
    pub block_gas_limit: u64,
}

impl Default for QuineConfig {
    fn default() -> Self {
        Self {
            max_bytecode_size: 24 * 1024, // 24 KiB
            gas_buffer_multiplier: 1.1,
            block_gas_limit: 30_000_000,
        }
    }
}

/// Represents a self-referential bytecode structure
#[derive(Debug, Clone)]
pub struct QuineBytecode {
    /// The actual bytecode
    pub bytecode: Vec<u8>,
    /// SHA3 hash of the bytecode for self-verification
    pub bytecode_hash: [u8; 32],
    /// Estimated gas cost for deployment
    pub deployment_gas: u64,
    /// Offset where the self-hash is embedded
    pub self_hash_offset: usize,
}

impl QuineBytecode {
    /// Create a new quine bytecode
    pub fn new(
        bytecode: Vec<u8>,
        bytecode_hash: [u8; 32],
        deployment_gas: u64,
        self_hash_offset: usize,
    ) -> Self {
        Self {
            bytecode,
            bytecode_hash,
            deployment_gas,
            self_hash_offset,
        }
    }

    /// Verify the bytecode integrity
    pub fn verify_integrity(&self) -> QuineResult<()> {
        // In production, this would use keccak256 to verify the hash
        // For now, we verify the stored hash is non-zero
        if self.bytecode_hash.iter().all(|&b| b == 0) {
            return Err(QuineError::HashMismatch);
        }
        
        Ok(())
    }

    /// Check if bytecode fits within EVM limits
    pub fn fits_in_evm_limit(&self, config: &QuineConfig) -> bool {
        self.bytecode.len() <= config.max_bytecode_size
    }

    /// Check if gas estimate is within block limits
    pub fn gas_within_block_limit(&self, config: &QuineConfig) -> bool {
        let buffered_gas = (self.deployment_gas as f64 * config.gas_buffer_multiplier) as u64;
        buffered_gas <= config.block_gas_limit
    }
}

/// EVM Quine Generator - creates self-replicating bytecode
pub struct EvmQuineGenerator<'a> {
    config: QuineConfig,
    _marker: PhantomData<&'a ()>,
}

impl<'a> EvmQuineGenerator<'a> {
    /// Create a new generator with default config
    pub fn new() -> Self {
        Self {
            config: QuineConfig::default(),
            _marker: PhantomData,
        }
    }

    /// Create a new generator with custom config
    pub fn with_config(config: QuineConfig) -> Self {
        Self {
            config,
            _marker: PhantomData,
        }
    }

    /// Generate self-referential bytecode
    /// 
    /// The generated bytecode contains its own hash embedded at a specific offset,
    /// allowing it to verify its own integrity during execution.
    pub fn generate_quine(&self, logic_bytecode: &[u8]) -> QuineResult<QuineBytecode> {
        // Calculate total size needed
        let hash_size = 32; // SHA3 hash size
        let constructor_overhead = 64; // Estimate for constructor code
        let total_size = logic_bytecode.len() + hash_size + constructor_overhead;

        // Check against EVM bytecode size limit (AUDIT FIX: prevent gas exhaustion)
        if total_size > self.config.max_bytecode_size {
            return Err(QuineError::BytecodeTooLarge);
        }

        // Build the quine bytecode structure
        let mut bytecode = Vec::with_capacity(total_size);

        // 1. Constructor preamble (pushes hash to stack)
        bytecode.push(opcodes::PUSH32);
        // Placeholder for hash (will be filled after hashing)
        let hash_placeholder = vec![0u8; 32];
        bytecode.extend_from_slice(&hash_placeholder);

        // 2. Code copy sequence to embed hash in runtime code
        bytecode.push(opcodes::DUP1);
        bytecode.push(opcodes::PUSH1);
        bytecode.push(0x00); // destination offset
        bytecode.push(opcodes::CODECOPY);

        // 3. Original logic bytecode
        bytecode.extend_from_slice(logic_bytecode);

        // 4. Return sequence
        bytecode.push(opcodes::PUSH1);
        bytecode.push(0x00); // memory offset
        bytecode.push(opcodes::RETURN);

        // Calculate the offset where the hash will be embedded
        let self_hash_offset = 1; // After PUSH32 opcode

        // Compute the hash of the complete bytecode
        // In production: use tiny_keccak::Keccak::keccak256
        let bytecode_hash = Self::compute_hash(&bytecode);

        // Embed the actual hash
        bytecode[1..33].copy_from_slice(&bytecode_hash);

        // Estimate deployment gas (AUDIT FIX: with safety buffer)
        let base_gas = 200_000 + (bytecode.len() as u64 * 16); // CREATE cost + data cost
        let deployment_gas = (base_gas as f64 * self.config.gas_buffer_multiplier) as u64;

        // Verify gas is within block limits
        if deployment_gas > self.config.block_gas_limit {
            return Err(QuineError::GasEstimateFailed);
        }

        let quine_bytecode = QuineBytecode::new(
            bytecode,
            bytecode_hash,
            deployment_gas,
            self_hash_offset,
        );

        // Final integrity check
        quine_bytecode.verify_integrity()?;

        Ok(quine_bytecode)
    }

    /// Compute SHA3-256 hash of bytecode
    fn compute_hash(bytecode: &[u8]) -> [u8; 32] {
        // Simplified hash computation
        // In production: use tiny_keccak::keccak256
        let mut hash = [0u8; 32];
        let mut running_hash = 0u64;
        
        for (i, &byte) in bytecode.iter().enumerate() {
            running_hash = running_hash.wrapping_add((byte as u64).wrapping_mul(i as u64 + 1));
            running_hash = running_hash.wrapping_mul(1099511628211);
        }
        
        hash[..8].copy_from_slice(&running_hash.to_le_bytes());
        hash
    }

    /// Optimize bytecode for gas efficiency (bytecode golfling)
    pub fn optimize_for_gas(&self, bytecode: &mut Vec<u8>) -> QuineResult<()> {
        // Simple optimization: replace PUSH1 0x00 sequences with more efficient ops
        let mut i = 0;
        while i < bytecode.len().saturating_sub(2) {
            // Detect PUSH1 0x00 pattern
            if bytecode[i] == opcodes::PUSH1 && bytecode[i + 1] == 0x00 {
                // Could replace with more efficient sequence if context allows
                // This is a simplified example
            }
            i += 1;
        }

        // Re-verify size after optimization
        if bytecode.len() > self.config.max_bytecode_size {
            return Err(QuineError::BytecodeTooLarge);
        }

        Ok(())
    }

    /// Generate a minimal quine template
    pub fn generate_minimal_template(&self) -> QuineResult<QuineBytecode> {
        // Minimal self-referential contract:
        // Returns its own code when called
        
        let minimal_logic = vec![
            opcodes::PUSH1, 0x00, // PUSH 0
            opcodes::DUP1,        // DUP1
            opcodes::PUSH1, 0x0A, // PUSH length (placeholder)
            opcodes::CODECOPY,    // Copy code to memory
            opcodes::PUSH1, 0x00, // PUSH 0 (memory offset)
            opcodes::RETURN,      // Return
        ];

        self.generate_quine(&minimal_logic)
    }
}

impl Default for EvmQuineGenerator<'_> {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_minimal_quine() {
        let generator = EvmQuineGenerator::new();
        let result = generator.generate_minimal_template();
        assert!(result.is_ok());
        
        let quine = result.unwrap();
        assert!(quine.fits_in_evm_limit(&QuineConfig::default()));
        assert!(quine.gas_within_block_limit(&QuineConfig::default()));
    }

    #[test]
    fn test_bytecode_too_large() {
        let generator = EvmQuineGenerator::new();
        let large_logic = vec![0u8; 30_000]; // Exceeds 24 KiB limit
        
        let result = generator.generate_quine(&large_logic);
        assert_eq!(result, Err(QuineError::BytecodeTooLarge));
    }
}
